"""
split_references.py

Splits Docling-converted whitepaper markdown (course_markdowns/*.md) into a
references/ tree, organized by heading, with an _index.md per whitepaper.

This is a MECHANICAL split — no LLM calls, no summarization, no rewriting.
The goal is a faithful, citable ground-truth layer that skills can point to
for "why" context, separate from the LLM-generated procedural skills in
skills_refined/.

Usage:
    python split_references.py --course "course-1-ai-agents-intensive"

Assumes:
    course_markdowns/<paper-name>.md  (Docling output, ATX headings: #, ##, ###)

Produces:
    references/<course>/<paper-name>/
        _index.md              <- table of contents, one line per section
        01-<section-slug>.md
        02-<section-slug>.md
        ...

Design notes:
- Splits on H1/H2 by default (SPLIT_LEVELS). H3+ stays nested inside its
  parent section file rather than fragmenting further — keeps section files
  in the ~500-1500 word range without going so granular that cross-references
  break.
- The _index.md summary line is extracted mechanically (first non-empty line
  of body text under that heading), NOT generated by an LLM. If a section has
  no body text before its first subheading (e.g. a heading immediately
  followed by another heading), the summary is left blank rather than invented.
- Page-number / header-footer cruft that Docling sometimes leaves behind
  (isolated numeric lines, repeated running headers) is stripped heuristically.
  This is intentionally conservative: when in doubt, keep the line. Verify
  a sample of output against the source PDF per your own review process.
"""

import argparse
import logging
import re
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

SOURCE_DIR = Path("course_markdowns")
OUTPUT_DIR = Path("references")

# Which heading levels start a new section file. H1/H2 -> new file.
# H3+ stays inline within whatever section file it falls under.
SPLIT_LEVELS = (1, 2)

SKIP_HEADINGS = {"acknowledgement", "table of content", "endnote", "appendix", "author", "license", "disclaimer"}

HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")

# Heuristics for stripping Docling page-artifact lines. Conservative on purpose.
PAGE_NUMBER_LINE_RE = re.compile(r"^\s*\d{1,4}\s*$")
LONE_PAGE_MARKER_RE = re.compile(r"^\s*(page\s+\d+|--- page \d+ ---)\s*$", re.IGNORECASE)


def sanitize_slug(text: str) -> str:
    """Turn a heading into a filesystem-safe slug."""
    slug = re.sub(r"[^a-zA-Z0-9\- ]", "", text.lower()).strip()
    slug = re.sub(r"\s+", "-", slug)
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug or "section"


def strip_page_artifacts(lines: list[str]) -> list[str]:
    """Drop lines that are almost certainly Docling page-number/header cruft.

    Conservative: only strips lines that are ENTIRELY a bare number or an
    explicit page marker on their own line. Never touches lines that contain
    other text, even if they also contain a number.
    """
    cleaned = []
    for line in lines:
        if PAGE_NUMBER_LINE_RE.match(line) or LONE_PAGE_MARKER_RE.match(line):
            continue
        cleaned.append(line)
    return cleaned


def first_summary_line(body_lines: list[str]) -> str:
    """Mechanically pull the first non-empty prose line as the index summary.

    Does not invent or paraphrase content. If nothing usable is found
    (e.g. section is immediately a subheading, table, or code block),
    returns an empty string rather than guessing.
    """
    for line in body_lines:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            break  # hit a subheading before any prose — nothing to summarize
        if stripped.startswith("```") or stripped.startswith("|"):
            break  # code block or table opener — don't try to summarize
        return stripped
    return ""


def split_document(md_path: Path) -> list[dict]:
    """Parse a single markdown file into a list of section dicts:
    {level, title, slug, lines (raw body, including subheadings)}
    """
    raw_lines = md_path.read_text(encoding="utf-8").splitlines()
    lines = strip_page_artifacts(raw_lines)

    sections = []
    current = None

    for line in lines:
        match = HEADING_RE.match(line)
        if match:
            level = len(match.group(1))
            title = match.group(2).strip()
            if level in SPLIT_LEVELS:
                if current is not None:
                    if not any(skip in current["title"].lower() for skip in SKIP_HEADINGS):
                        sections.append(current)
                current = {"level": level, "title": title, "lines": []}
                continue
        if current is None:
            # content before the first split-level heading — bucket it as
            # a preamble section so nothing is silently dropped
            current = {"level": 0, "title": "Preamble", "lines": []}
        current["lines"].append(line)

    if current is not None:
        if not any(skip in current["title"].lower() for skip in SKIP_HEADINGS):
            sections.append(current)

    # de-duplicate slugs within a document (e.g. repeated "Overview" headings)
    seen_slugs: dict[str, int] = {}
    for sec in sections:
        base_slug = sanitize_slug(sec["title"])
        count = seen_slugs.get(base_slug, 0)
        seen_slugs[base_slug] = count + 1
        sec["slug"] = base_slug if count == 0 else f"{base_slug}-{count + 1}"

    return sections


def write_paper_references(md_path: Path, course_slug: str) -> None:
    paper_slug = sanitize_slug(md_path.stem)
    paper_dir = OUTPUT_DIR / course_slug / paper_slug
    paper_dir.mkdir(parents=True, exist_ok=True)

    sections = split_document(md_path)
    if not sections:
        logger.warning(f"No headings found in {md_path.name} — skipping split, copying whole file.")
        (paper_dir / "01-full-document.md").write_text(
            md_path.read_text(encoding="utf-8"), encoding="utf-8"
        )
        return

    index_lines = [f"# {md_path.stem} — Section Index\n"]

    for i, sec in enumerate(sections, 1):
        filename = f"{i:02d}-{sec['slug']}.md"
        body_text = "\n".join(sec["lines"]).strip()

        heading_prefix = "#" * max(sec["level"], 1)
        file_content = f"{heading_prefix} {sec['title']}\n\n{body_text}\n" if body_text else f"{heading_prefix} {sec['title']}\n"
        (paper_dir / filename).write_text(file_content, encoding="utf-8")

        summary = first_summary_line(sec["lines"])
        index_lines.append(f"- **[{sec['title']}]({filename})** — {summary}" if summary else f"- **[{sec['title']}]({filename})**")

    (paper_dir / "_index.md").write_text("\n".join(index_lines) + "\n", encoding="utf-8")
    logger.info(f"{md_path.name}: wrote {len(sections)} section files + _index.md to {paper_dir}")


def main():
    parser = argparse.ArgumentParser(description="Split course markdown into referenceable sections.")
    parser.add_argument("--course", default="google-ai-agents-intensive", help="Course slug, e.g. 'course-1-ai-agents-intensive'")
    parser.add_argument("--source-dir", default=str(SOURCE_DIR), help="Directory of Docling markdown files")
    args = parser.parse_args()

    source_dir = Path(args.source_dir)
    if not source_dir.exists():
        logger.error(f"Source directory {source_dir} does not exist.")
        return

    md_files = list(source_dir.glob("*.md"))
    if not md_files:
        logger.warning(f"No markdown files found in {source_dir}.")
        return

    logger.info(f"Splitting {len(md_files)} markdown files for course '{args.course}'...")
    for md_path in md_files:
        write_paper_references(md_path, args.course)

    logger.info("Done. Spot-check a sample of _index.md files against source PDFs before trusting output.")


if __name__ == "__main__":
    main()
